Little_Helper/App_Login/urls.py
from django.urls import path
from . import views
app_name = 'App_Login'

urlpatterns = [
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('profile/', views.profile, name='profile'),
    path('change_picture/', views.edit_profile_pic, name='edit_picture'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),

]

Little_Helper/App_Task/urls.py
from django.urls import path
from . import views

app_name = 'App_Task'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('create_task/', views.create_task, name='create_task'),
    path('task/<slug:slug>/', views.view_task, name='current_task'),
    path('delete/<slug:slug>/', views.delete_task, name='delete'),
    path('edit_task/<slug:slug>', views.edit_task, name='edit_task'),

]

Little_Helper/Little_Helper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='landing_page'),
    path('account/', include('App_Login.urls')),
    path('task/', include('App_Task.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Little_Helper/App_Login/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    profile_picture = models.ImageField(upload_to='Profile_Pictures', blank=True)

Little_Helper/App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import UserProfile


class CreateNewUser(UserCreationForm):
    username = forms.CharField(required=True, label="", widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password1 = forms.CharField(required=True, label="",
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(required=True, label="",
                                widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')


class EditProfile(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name')

    # # we modify the init method to keep the password field removed from our rendered fields to be changed
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.pop('password', None)


class ProfilePicture(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_picture',)

Little_Helper/App_Login/views.py
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import UserProfile
from .forms import CreateNewUser, ProfilePicture, EditProfile


# Create your views here.
# sign_up view
def sign_up(request):
    form = CreateNewUser()

    if request.method == 'POST':
        form = CreateNewUser(request.POST)

        if form.is_valid():
            user = form.save()
            user_profile = UserProfile(user=user)
            user_profile.save()
            return HttpResponseRedirect(reverse('App_Login:sign_in'))
    return render(request, 'App_Login/sign_up.html', context={'title': 'Sign Up', 'form': form})


# sign_in view
def sign_in(request):
    form = AuthenticationForm()

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('App_Task:home'))

    return render(request, 'App_Login/sign_in.html', context={'form': form, 'title': 'Sign In'})


# view to logout
@login_required
def sign_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('landing_page'))


@login_required
def profile(request):
    return render(request, 'App_Login/profile.html', context={'title': 'Profile Page'})


# view to edit profile picture
@login_required
def edit_profile_pic(request):
    form = ProfilePicture(instance=request.user.user_profile)

    if request.method == 'POST':
        form = ProfilePicture(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save(commit=True)
            return HttpResponseRedirect(reverse('App_Login:profile'))

    return render(request, 'App_Login/edit_prof_pic.html', context={'title': 'Profile Picture', 'form': form})


# edit internal parts of profile-- first name, last name, username
@login_required
def edit_profile(request):
    form = EditProfile(instance=request.user)

    if request.method == 'POST':
        form = EditProfile(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))

    return render(request, 'App_Login/edit_profile.html', context={'title': 'Edit Profile', 'form': form})


# password change
@login_required
def change_password(request):
    form = PasswordChangeForm(request.user)

    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # To prevent the user from being logged out
            messages.success(request, 'Your password was successfully updated!')
            return HttpResponseRedirect(reverse('App_Login:edit_profile'))
        else:
            messages.error(request, 'Please correct the errors below.')
    return render(request, 'App_Login/change_password.html', context={'title': 'Password change', 'form': form})

Little_Helper/templates/App_Login/change_password.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
 {{ title }}
{% endblock %}

{% block body_content %}

<form method="POST">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">Submit</button>
</form>
{% endblock %}

Little_Helper/templates/App_Login/edit_prof_pic.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
 {{ title }}
{% endblock %}

{% block body_content %}

<form method="POST" enctype="multipart/form-data">
    {{ form }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">Submit</button>
</form>


{% endblock %}

Little_Helper/templates/App_Login/edit_profile.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
 {{ title }}
{% endblock %}

{% block body_content %}

<form method="POST">
    {{ form|crispy }}
    {% csrf_token %}
    <a href="{% url 'App_Login:change_password' %}">Edit Password</a>
    <br>
    <button type="submit" class="btn btn-success btn-sm">Update</button>
</form>
{% endblock %}

Little_Helper/templates/App_Login/profile.html
{% extends 'navbar.html' %}

{% block title_block %}
 {{ title }}
{% endblock %}

{% block body_content %}
 <div class="row">
    <div class="col-sm-4">
        {% if user.user_profile.profile_picture %}
        <a class="nav-item nav-link" href="{% url 'App_Login:edit_picture' %}"><img src="/media/{{ user.user_profile.profile_picture }}" alt="Image" width="220px" height="220px" class="rounded-circle"> </a>
        {% else %}
        <a class="nav-item nav-link" href="{% url 'App_Login:edit_picture' %}"><img src="/media/Profile_Pictures/default.png" alt="Default Image" width="220px" height="220px" class="rounded-circle"> </a>
        {% endif %}
    </div>

    <div class="col-sm-8">
        <br>
        <br>
        <br>
        <h3>{{ user.username }}<a href="{% url 'App_Login:edit_profile' %}" class="btn btn-light btn-sm">Edit Profile</a></h3>
    </div>

</div>

{% endblock %}

Little_Helper/templates/App_Login/sign_In.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
    {{ title }}
{% endblock %}

{% block css_block %}
<style>
    .sign_up{
        width:550px;
        border:1px solid #ccc;
        padding: 60px;
    }

    .sign_in{
        width: 550px;
        border:1px solid #ccc;
        padding: 30px
    }
</style>
{% endblock %}

{% block body_content %}
<center>
    <div class="sign_in">
        <h3>Sign In</h3>
        <form method="POST" >
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-primary btn-sm">Sign In</button>
        </form>
    </div>
    <div class="sign_up">
        <p>Don't have an account?<a href="{% url 'App_Login:sign_up' %}">Sign_Up</a></p>
    </div>
</center>

{% endblock %}

Little_Helper/templates/App_Login/sign_up.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
    {{ title }}
{% endblock %}

{% block css_block %}
<style>
    .sign_up{
        width:550px;
        border:1px solid #ccc;
        padding: 60px;
    }

    .sign_in{
        width: 550px;
        border:1px solid #ccc;
        padding: 30px
    }
</style>
{% endblock %}

{% block body_content %}
<center>
    <div class="sign_up">
        <h3>Sign Up</h3>
        <form method="POST" >
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-primary btn-sm">Sign Up</button>
        </form>
    </div>
    <div class="sign_in">
        <p>Have an account?<a href="{% url 'App_Login:sign_in' %}">Sign In</a></p>
    </div>
</center>

{% endblock %}