Little_Helper/App_Task/urls.py
from django.urls import path
from . import views

app_name = 'App_Task'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('create_task/', views.create_task, name='create_task'),
    path('task/<slug:slug>/', views.view_task, name='current_task'),
    path('delete/<slug:slug>/', views.delete_task, name='delete'),
    path('edit_task/<slug:slug>', views.edit_task, name='edit_task'),

]

Little_Helper/Little_Helper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='landing_page'),
    path('account/', include('App_Login.urls')),
    path('task/', include('App_Task.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Little_Helper/App_Task/models.py
from datetime import date

from django.contrib.auth.models import User
from django.db import models
from django.core.validators import MinValueValidator

# Create your models here.

class Task(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='all_tasks')
    task_name = models.CharField(max_length=512, blank=False)
    task_date = models.DateField(blank=False, validators=[MinValueValidator(limit_value=date.today(), message='Date cannot be in the past')])
    task_time = models.TimeField(blank=False)
    task_description = models.TextField(max_length=1000, blank=True)
    # slug for identification of a task when task needs to be modified(using this instead of a primary key
    task_slug = models.SlugField(null=True, unique=True)

    def __str__(self):
        return self.task_name

    class Meta:
        # this is an alternative order on how we want the blogs to be ordered
        ordering = ['task_date', 'task_time']

Little_Helper/App_Task/forms.py
from django import forms
from .models import Task


# forms


class CreateTask(forms.ModelForm):
    task_name = forms.CharField(label='Task Name')
    task_date = forms.DateField(label='Task Date', widget=forms.TextInput(attrs={'type': 'date', }))
    task_time = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}))
    task_description = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Describe task to your future self'}))

    class Meta:
        model = Task
        exclude = ('author', 'task_slug')

Little_Helper/App_Task/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .forms import CreateTask
import uuid

# Create your views here.
from .models import Task


@login_required
def home(request):
    return render(request, 'App_Task/home.html', context={'title': 'Home'})


@login_required
def create_task(request):
    form = CreateTask()
    if request.method == 'POST':
        form = CreateTask(request.POST)
        if form.is_valid():
            tsk = form.save(commit=False)
            tsk.author = request.user
            name = tsk.task_name
            tsk.task_slug = name.replace(" ", "-") + "-" + str(uuid.uuid4())
            tsk.save()
            return HttpResponseRedirect(reverse('App_Task:home'))

    return render(request, 'App_Task/create_tsk.html', context={'title': 'Create Task', 'form': form})


@login_required
def view_task(request, slug):
    curr_task = Task.objects.get(task_slug=slug)

    return render(request, 'App_Task/task.html', context={'task': curr_task, 'title': 'Task'})


@login_required
def delete_task(request, slug):
    task = Task.objects.get(task_slug=slug)
    task.delete()

    return render(request, 'App_Task/home.html', context={})


@login_required
def edit_task(request, slug):
    # using reverse relationship between user and task
    current_task = request.user.all_tasks.get(task_slug=slug)
    form = CreateTask(instance=current_task)

    init_name = current_task.task_name

    if request.method == "POST":
        form = CreateTask(request.POST, instance=current_task)
        if form.is_valid:
            task = form.save(commit=False)
            #         update slug, incase the task name is changed
            name = task.task_name
            if init_name != name:
                task.task_slug = name.replace(" ", "-") + "-" + str(uuid.uuid4())
            task.save()
            return HttpResponseRedirect(reverse('App_Task:current_task', kwargs={'slug': task.task_slug}))

    return render(request, 'App_Task/edit_task.html', context={'task': current_task, 'form': form})

Little_Helper/templates/App_Task/create_tsk.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
    {{ title }}
{% endblock %}


{% block body_content %}
<center>
        <h3>Create new task</h3>
        <form method="POST" >
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-primary btn-sm">Finish</button>
        </form>
</center>

{% endblock %}

Little_Helper/templates/App_Task/edit_task.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
    {{ title }}
{% endblock %}


{% block body_content %}
<center>
        <h3>Edit Task</h3>
        <form method="POST" >
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-primary btn-sm">Finish</button>
        </form>
</center>

{% endblock %}

Little_Helper/templates/App_Task/home.html
{% extends 'navbar.html' %}

{% block title_block %}
 {{ title }}
{% endblock %}

{% block body_content %}

<a href="{% url 'App_Task:create_task' %}" class="btn btn-primary btn-sm">Create New Task</a>
<h1>Already in the home page</h1>
{% for task in user.all_tasks.all  %}
 <a href="{% url 'App_Task:current_task' slug=task.task_slug %}"><h3>{{ task.task_name }}</h3></a>
 <p>{{ task.task_date }}</p>
{% endfor %}
{% endblock %}

Little_Helper/templates/App_Task/task.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
    {{ title }}
{% endblock %}


{% block body_content %}
<h2>{{ task.task_name }}</h2>
<p> {{ task.task_description }}</p>
<p><b>{{ task.task_date}} &nbsp; {{ task.task_time }}</b> </p>
<a href="{% url 'App_Task:edit_task' slug=task.task_slug %}" class="btn btn-primary btn-sm">Edit Task</a>
<a href="{% url 'App_Task:delete' slug=task.task_slug %}" class="btn btn-danger btn-sm">Delete Task</a>
{% endblock %}